# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "landlock-observability"
version = "0.0.0"
edition = "2021"
rust-version = "1.88"
license = "(MIT OR Apache-2.0) AND GPL-2.0-only"
repository = "https://github.com/landlock-lsm/landlock-observability"
description = "Reusable observability for Landlock"
readme = "README.md"
keywords = ["landlock", "linux", "security", "observability", "bpf"]
categories = ["os::linux-apis"]

[dependencies]
libbpf-rs = "0.24"

[build-dependencies]
libbpf-cargo = "0.24"

[dev-dependencies]
landlock = "0.4.7"
nix = { version = "0.31", default-features = false, features = [
    "process",
    "ptrace",
    "signal",
] }
wait-timeout = "0.2.1"

[workspace]
members = ["lltop"]
resolver = "2"
