// SPDX-License-Identifier: MIT OR Apache-2.0

// Generated by scripts/generate-access-names.py; do not edit.

#[rustfmt::skip]
pub(crate) const FILESYSTEM_ACCESS_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "execute"),
    (1_u64 << 2, "read_file"),
];

#[rustfmt::skip]
pub(crate) const NETWORK_ACCESS_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "bind_tcp"),
    (1_u64 << 1, "connect_tcp"),
];

#[rustfmt::skip]
pub(crate) const SCOPE_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "abstract_unix_socket"),
    (1_u64 << 1, "signal"),
];
