// SPDX-License-Identifier: MIT OR Apache-2.0

// Generated by scripts/generate-access-names.py; do not edit.

#[rustfmt::skip]
pub(crate) const FILESYSTEM_ACCESS_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "execute"),
    (1_u64 << 1, "write_file"),
    (1_u64 << 2, "read_file"),
    (1_u64 << 3, "read_dir"),
    (1_u64 << 4, "remove_dir"),
    (1_u64 << 5, "remove_file"),
    (1_u64 << 6, "make_char"),
    (1_u64 << 7, "make_dir"),
    (1_u64 << 8, "make_reg"),
    (1_u64 << 9, "make_sock"),
    (1_u64 << 10, "make_fifo"),
    (1_u64 << 11, "make_block"),
    (1_u64 << 12, "make_sym"),
    (1_u64 << 13, "refer"),
    (1_u64 << 14, "truncate"),
    (1_u64 << 15, "ioctl_dev"),
    (1_u64 << 16, "resolve_unix"),
];

#[rustfmt::skip]
pub(crate) const NETWORK_ACCESS_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "bind_tcp"),
    (1_u64 << 1, "connect_tcp"),
    (1_u64 << 2, "bind_udp"),
    (1_u64 << 3, "connect_send_udp"),
];

#[rustfmt::skip]
pub(crate) const SCOPE_NAMES: &[(u64, &str)] = &[
    (1_u64 << 0, "abstract_unix_socket"),
    (1_u64 << 1, "signal"),
];
